import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import { toPrintCurrencyText } from "./formatCurrency.js";
import { ensurePdfUnicodeFont } from "./pdfUnicodeFont.js";
import {
  RFS_PALETTE as PALETTE,
  distributeColumnWidths,
  drawAllReportFooters,
  fmtInrPdf,
  fmtPdfText,
  getPageLayout,
  loadLogoDataUrl,
} from "./pdfReportLayout";

const MARGIN = 10;
const FOOTER_RESERVE = 16;
const DEFAULT_FOOTER = "Generated by Ruthra Financial Solutions ERP";

export function enterpriseStatusTextColor(status) {
  const s = String(status || "").toLowerCase();
  if (s.includes("approv")) return PALETTE.accent;
  if (s.includes("reject") || s.includes("declin")) return PALETTE.danger;
  if (s.includes("collect") && !s.includes("partial")) return PALETTE.success;
  if (s.includes("overdue") || s.includes("skip")) return PALETTE.danger;
  if (s.includes("pend") || s.includes("partial") || s.includes("resched")) return PALETTE.warn;
  return PALETTE.inkSoft;
}

function truncateLines(doc, text, maxWidth, maxLines = 2) {
  const lines = doc.splitTextToSize(String(text ?? ""), maxWidth);
  if (lines.length <= maxLines) return lines;
  return [...lines.slice(0, maxLines - 1), `${lines[maxLines - 1]}…`];
}

async function drawPremiumHeader(doc, layout, origin, meta, pdfFont) {
  const { margin, pageWidth } = layout;
  const bandH = 28;

  doc.setFillColor(...PALETTE.headerBand);
  doc.rect(0, 0, pageWidth, bandH, "F");
  doc.setDrawColor(...PALETTE.accent);
  doc.setLineWidth(0.55);
  doc.line(0, bandH, pageWidth, bandH);

  const logoW = 18;
  const logoH = 12;
  const logoY = 8;
  let textX = margin;

  const logoDataUrl = await loadLogoDataUrl(origin);
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, "PNG", margin, logoY, logoW, logoH);
      textX = margin + logoW + 6;
    } catch {
      /* no logo */
    }
  }

  doc.setFont(pdfFont, "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PALETTE.ink);
  doc.text("Ruthra Financial Solutions", textX, 12);

  doc.setFontSize(10.5);
  doc.setTextColor(...PALETTE.accent);
  doc.text(meta.title || "Report", textX, 18);

  doc.setFont(pdfFont, "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...PALETTE.muted);
  const rightX = pageWidth - margin;
  doc.text(`Generated  ·  ${meta.generatedLabel}`, rightX, 11, { align: "right" });
  if (meta.reportId) doc.text(`Report ID  ·  ${meta.reportId}`, rightX, 15.5, { align: "right" });
  if (meta.preparedBy) doc.text(`Prepared by  ·  ${meta.preparedBy}`, rightX, 20, { align: "right" });

  doc.setFontSize(7.2);
  doc.text(meta.subtitle || "", textX, 23.5);

  return bandH + 4;
}

function drawMetaStrip(doc, layout, startY, filterLines, branch, pdfFont) {
  const { margin, contentW } = layout;
  const lines = [...(filterLines || [])];
  if (branch) lines.unshift(`Center / branch: ${branch}`);

  if (!lines.length) return startY;

  const pad = 4;
  const lineH = 4.2;
  const panelH = pad * 2 + Math.max(1, lines.length) * lineH;

  doc.setFillColor(...PALETTE.surfaceAlt);
  doc.setDrawColor(...PALETTE.line);
  doc.setLineWidth(0.2);
  doc.roundedRect(margin, startY, contentW, panelH, 2, 2, "FD");

  doc.setFont(pdfFont, "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...PALETTE.inkSoft);
  let y = startY + pad + 3;
  lines.forEach((line) => {
    doc.text(fmtPdfText(line), margin + pad, y);
    y += lineH;
  });

  return startY + panelH + 3;
}

function drawKpiCards(doc, layout, startY, cards, pdfFont) {
  const { margin, contentW } = layout;
  const items = (cards || []).slice(0, 6);
  if (!items.length) return startY;

  const cols = Math.min(6, items.length);
  const gap = 3;
  const cardW = (contentW - gap * (cols - 1)) / cols;
  const cardH = 16;

  items.forEach((card, i) => {
    const x = margin + i * (cardW + gap);
    doc.setFillColor(...PALETTE.surface);
    doc.setDrawColor(...PALETTE.line);
    doc.setLineWidth(0.2);
    doc.roundedRect(x, startY, cardW, cardH, 2, 2, "FD");

    doc.setFont(pdfFont, "normal");
    doc.setFontSize(6.8);
    doc.setTextColor(...PALETTE.muted);
    doc.text(String(card.label || "").toUpperCase(), x + 3, startY + 5);

    doc.setFont(pdfFont, "bold");
    doc.setFontSize(10);
    doc.setTextColor(...PALETTE.ink);
    doc.text(truncateLines(doc, toPrintCurrencyText(card.value ?? "—"), cardW - 6, 1), x + 3, startY + 11);

    if (card.note) {
      doc.setFont(pdfFont, "normal");
      doc.setFontSize(6.2);
      doc.setTextColor(...PALETTE.muted);
      doc.text(truncateLines(doc, toPrintCurrencyText(card.note), cardW - 6, 1), x + 3, startY + 14.5);
    }
  });

  return startY + cardH + 5;
}

/**
 * Build a premium tabular PDF (landscape or portrait A4).
 *
 * @param {Object} payload
 * @param {string[]} payload.headers — column titles
 * @param {(row: *) => string[]} payload.mapRowToCells
 * @param {Array} [payload.rows]
 * @param {number[]} [payload.columnRatios]
 * @param {number[]} [payload.statusColumnIndices]
 * @param {number[]} [payload.currencyColumnIndices]
 * @param {"landscape"|"portrait"} [payload.orientation]
 */
export async function buildEnterpriseTabularReportPdf(payload) {
  const {
    rows = [],
    headers = [],
    mapRowToCells,
    title = "Report",
    subtitle = "",
    filterLines = [],
    summaryCards = [],
    reportMeta = {},
    origin = typeof window !== "undefined" ? window.location.origin : "",
    orientation = "landscape",
    columnRatios,
    statusColumnIndices = [],
    currencyColumnIndices = [],
    columnKeys = [],
    getRowAlert,
    footerNote = DEFAULT_FOOTER,
    tableFontSize = 7.5,
  } = payload;

  const generatedLabel =
    reportMeta.generatedLabel ||
    new Date().toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" });

  const doc = new jsPDF({ orientation, unit: "mm", format: "a4" });
  const pdfFont = await ensurePdfUnicodeFont(doc, origin);
  const layout = getPageLayout(doc, { margin: MARGIN, footerReserve: FOOTER_RESERVE });

  let y = await drawPremiumHeader(doc, layout, origin, {
    title,
    subtitle,
    generatedLabel,
    reportId: reportMeta.reportId,
    preparedBy: reportMeta.preparedBy,
  }, pdfFont);

  y = drawMetaStrip(doc, layout, y, filterLines, reportMeta.branch || reportMeta.center, pdfFont);
  y = drawKpiCards(doc, layout, y, summaryCards, pdfFont);

  const ratios =
    columnRatios && columnRatios.length === headers.length
      ? columnRatios
      : headers.map(() => 1 / Math.max(1, headers.length));

  const colWidths = distributeColumnWidths(layout.contentW, ratios);
  const body = rows.map((row) => (mapRowToCells ? mapRowToCells(row) : row));

  const columnStyles = {};
  colWidths.forEach((w, i) => {
    columnStyles[i] = {
      cellWidth: w,
      halign: currencyColumnIndices.includes(i) ? "right" : "left",
    };
  });

  autoTable(doc, {
    startY: y,
    head: [headers],
    body,
    margin: { left: MARGIN, right: MARGIN, bottom: FOOTER_RESERVE },
    showHead: "everyPage",
    rowPageBreak: "auto",
    tableLineWidth: 0.15,
    tableLineColor: PALETTE.line,
    styles: {
      font: pdfFont,
      fontSize: tableFontSize,
      cellPadding: { top: 2.4, right: 1.8, bottom: 2.4, left: 1.8 },
      textColor: PALETTE.ink,
      lineColor: PALETTE.lineSoft,
      lineWidth: 0.1,
      valign: "middle",
      overflow: "linebreak",
    },
    headStyles: {
      font: pdfFont,
      fillColor: PALETTE.headBg,
      textColor: PALETTE.headText,
      fontStyle: "bold",
      fontSize: Math.min(8, tableFontSize + 0.5),
      halign: "center",
      cellPadding: { top: 3, right: 1.8, bottom: 3, left: 1.8 },
    },
    bodyStyles: { fillColor: PALETTE.surface },
    alternateRowStyles: { fillColor: PALETTE.surfaceAlt },
    columnStyles,
    didParseCell: (data) => {
      if (data.section !== "body") return;
      if (statusColumnIndices.includes(data.column.index)) {
        const status = data.cell.raw;
        data.cell.styles.textColor = enterpriseStatusTextColor(status);
        data.cell.styles.fontStyle = "bold";
        return;
      }
      if (!getRowAlert || !rows.length) return;
      const sourceRow = rows[data.row.index];
      const alert = getRowAlert(sourceRow);
      if (!alert || alert.kind === "none") return;
      const colKey = columnKeys[data.column.index];
      const pdfSoftFills = {
        dangerSoft: [255, 228, 230],
        warnSoft: [254, 243, 199],
      };
      if (alert.scope === "customerIdCell" && colKey === "customerId" && alert.pdfFill) {
        data.cell.styles.fillColor = pdfSoftFills[alert.pdfFill] || PALETTE.surface;
        return;
      }
      if (!alert.pdfColor) return;
      const pdfColor = alert.pdfColor === "warn" ? PALETTE.warn : PALETTE.danger;
      if (alert.scope === "fullRow") {
        data.cell.styles.textColor = pdfColor;
      }
    },
  });

  drawAllReportFooters(doc, `${footerNote}  ·  ${generatedLabel}`, MARGIN);
  doc.setPage(1);
  return doc;
}

export async function downloadEnterpriseTabularPdf(payload, filenamePrefix = "report") {
  const doc = await buildEnterpriseTabularReportPdf(payload);
  const stamp = new Date().toISOString().slice(0, 10);
  const id = String(payload?.reportMeta?.reportId || "export").replace(/[^\w-]+/g, "_");
  doc.save(`${filenamePrefix}-${stamp}-${id}.pdf`);
}

export async function printEnterpriseTabularPdf(payload) {
  const doc = await buildEnterpriseTabularReportPdf(payload);
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank", "noopener,noreferrer");
  const cleanup = () => URL.revokeObjectURL(url);
  if (!win) {
    cleanup();
    await downloadEnterpriseTabularPdf(payload);
    return;
  }
  setTimeout(() => {
    try {
      win.focus();
      win.print();
    } catch {
      /* ignore */
    }
  }, 650);
  setTimeout(cleanup, 120_000);
}

/** Build PDF payload from EnterpriseReportPreview column/row shapes. */
export function buildPreviewColumnsPdfPayload({
  title,
  subtitle = "",
  columns = [],
  rows = [],
  filterLines = [],
  summaryCards = [],
  reportMeta = {},
  orientation,
  getRowAlert,
}) {
  const headers = columns.map((c) => c.label);
  const statusColumnIndices = columns.map((c, i) => (c.cellType === "status" ? i : -1)).filter((i) => i >= 0);
  const currencyColumnIndices = columns.map((c, i) => (c.cellType === "currency" ? i : -1)).filter((i) => i >= 0);
  const ori = orientation || (headers.length > 8 ? "landscape" : "portrait");

  return {
    title,
    subtitle,
    filterLines,
    summaryCards,
    reportMeta,
    orientation: ori,
    headers,
    rows,
    mapRowToCells: (row) =>
      columns.map((col) => {
        const val = row[col.key];
        if (col.cellType === "currency") return fmtInrPdf(Number(val || 0));
        return fmtPdfText(val ?? "-");
      }),
    statusColumnIndices,
    currencyColumnIndices,
    columnKeys: columns.map((column) => column.key),
    getRowAlert,
    tableFontSize: headers.length > 10 ? 6.8 : 7.5,
  };
}

/** Convert string-column tables (legacy print helpers) into tabular PDF payload. */
export function buildSimpleTablePdfPayload({
  title,
  subtitle = "",
  columns,
  rows,
  filterLines = [],
  summaryCards = [],
  reportMeta = {},
  orientation = "portrait",
}) {
  const headers = columns;
  const statusIdx = headers.findIndex((h) => /status|approval/i.test(String(h)));
  const currencyIdx = headers
    .map((h, i) => (/amount|salary|income|expense|profit|cash|value/i.test(String(h)) ? i : -1))
    .filter((i) => i >= 0);

  return {
    title,
    subtitle,
    headers,
    rows,
    mapRowToCells: (row) =>
      Array.isArray(row) ? row.map((c) => toPrintCurrencyText(String(c ?? ""))) : [],
    filterLines,
    summaryCards,
    reportMeta,
    orientation,
    statusColumnIndices: statusIdx >= 0 ? [statusIdx] : [],
    currencyColumnIndices: currencyIdx,
    tableFontSize: headers.length > 10 ? 6.8 : 7.5,
  };
}
