import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { fmtInrPdf as fmtInr, fmtPdfText } from "./pdfReportLayout.js";
import { ensurePdfUnicodeFont } from "./pdfUnicodeFont.js";

const PALETTE = {
  ink: [15, 23, 42],
  inkSoft: [51, 65, 85],
  muted: [100, 116, 139],
  line: [226, 232, 240],
  surface: [255, 255, 255],
  surfaceAlt: [248, 250, 252],
  headerTop: [239, 246, 255],
  headerBottom: [241, 250, 252],
  headBg: [30, 64, 175],
  headText: [248, 250, 252],
  accent: [37, 99, 235],
  success: [5, 122, 85],
  successBg: [220, 252, 231],
  warn: [180, 83, 9],
  warnBg: [254, 243, 199],
  danger: [185, 28, 28],
  dangerBg: [254, 226, 226],
  neutralBg: [241, 245, 249],
};

function fmtDate(value) {
  if (!value) return "-";
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return "-";
  return d.toLocaleDateString("en-GB");
}

function startOfDay(d) {
  const x = d instanceof Date ? d : new Date(d);
  if (Number.isNaN(x.getTime())) return null;
  return new Date(x.getFullYear(), x.getMonth(), x.getDate());
}

/** Display status + badge tone for PDF (Collected / Pending / Overdue / Skipped). */
function rowDisplayStatus(row) {
  const raw = String(row.latestStatus || "").trim().toLowerCase();
  const outstanding = Number(row.outstanding || 0);
  const due = row.dueDate ? startOfDay(row.dueDate) : null;
  const today = startOfDay(new Date());

  if (raw === "skipped") return { label: "Skipped", tone: "gray" };
  if (raw === "collected") return { label: "Collected", tone: "green" };
  if (outstanding > 0 && due && due.getTime() < today.getTime()) return { label: "Overdue", tone: "red" };
  return { label: "Pending", tone: "orange" };
}

function statusCellStyle(tone) {
  switch (tone) {
    case "green":
      return { fillColor: PALETTE.successBg, textColor: PALETTE.success, fontStyle: "bold" };
    case "orange":
      return { fillColor: PALETTE.warnBg, textColor: PALETTE.warn, fontStyle: "bold" };
    case "red":
      return { fillColor: PALETTE.dangerBg, textColor: PALETTE.danger, fontStyle: "bold" };
    default:
      return { fillColor: PALETTE.neutralBg, textColor: PALETTE.muted, fontStyle: "bold" };
  }
}

async function loadLogoDataUrl(origin) {
  const base = (origin || "").replace(/\/$/, "");
  try {
    const res = await fetch(`${base}/branding/ruthra-logo.png`);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => reject(new Error("read fail"));
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function drawFooter(doc, pageIndex, totalPages, generatedLabel, pdfFont) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerTop = pageHeight - 16;

  doc.setDrawColor(...PALETTE.line);
  doc.setLineWidth(0.3);
  doc.line(12, footerTop, pageWidth - 12, footerTop);

  doc.setFont(pdfFont, "normal");
  doc.setFontSize(7);
  doc.setTextColor(...PALETTE.muted);
  doc.text("Generated by Ruthra Financial Solutions", 12, footerTop + 4);

  doc.setTextColor(...PALETTE.inkSoft);
  doc.text(`Page ${pageIndex} of ${totalPages}`, pageWidth / 2, footerTop + 4, { align: "center" });

  doc.setTextColor(...PALETTE.muted);
  doc.text(fmtPdfText(generatedLabel), pageWidth - 12, footerTop + 4, { align: "right" });

  doc.setFontSize(6.5);
  doc.setTextColor(...PALETTE.muted);
  doc.text("Confidential - for authorised use only.", 12, footerTop + 8);
}

function drawAllFooters(doc, generatedLabel, pdfFont) {
  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i += 1) {
    doc.setPage(i);
    drawFooter(doc, i, total, generatedLabel, pdfFont);
  }
}

/**
 * @param {object} report — shape from computeReports + filtered detailRows
 * @param {{
 *   origin?: string;
 *   generatedLabel?: string;
 *   extraMetaLines?: string[];
 * }} [options]
 */
export async function buildLoanCollectionReportDoc(report, options = {}) {
  const origin = options.origin ?? (typeof window !== "undefined" ? window.location.origin : "");
  const margin = 12;
  const pageWidth = 210;
  const contentW = pageWidth - 2 * margin;
  const generatedLabel =
    typeof options.generatedLabel === "string" && options.generatedLabel.trim()
      ? options.generatedLabel.trim()
      : new Date().toLocaleString("en-IN");
  const extraMetaLines = Array.isArray(options.extraMetaLines)
    ? options.extraMetaLines.map((l) => String(l || "").trim()).filter(Boolean)
    : [];

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const pdfFont = await ensurePdfUnicodeFont(doc, origin);
  const m = report.metrics || {};

  doc.setPage(1);
  doc.setFont(pdfFont, "bold");
  doc.setFontSize(52);
  doc.setTextColor(241, 245, 249);
  doc.text("RFS", pageWidth / 2, 148, { align: "center", angle: 35 });

  const bandH = 34;
  doc.setFillColor(...PALETTE.headerTop);
  doc.rect(0, 0, pageWidth, bandH, "F");
  doc.setFillColor(...PALETTE.headerBottom);
  doc.rect(0, bandH - 6, pageWidth, 6, "F");
  doc.setDrawColor(...PALETTE.accent);
  doc.setLineWidth(0.45);
  doc.line(0, bandH, pageWidth, bandH);

  const logoW = 16;
  const logoH = 11;
  const logoY = 10;
  let textX = margin;

  const logoDataUrl = await loadLogoDataUrl(origin);
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, "PNG", margin, logoY, logoW, logoH);
      textX = margin + logoW + 5;
    } catch {
      /* ignore */
    }
  }

  doc.setFont(pdfFont, "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PALETTE.ink);
  doc.text("Ruthra Financial Solutions", textX, 14);

  doc.setFontSize(10);
  doc.setTextColor(...PALETTE.accent);
  doc.text("Loan Collection Report", textX, 20.5);

  doc.setFont(pdfFont, "normal");
  doc.setFontSize(7.8);
  doc.setTextColor(...PALETTE.inkSoft);
  doc.text(`Generated  |  ${generatedLabel}`, textX, 26);
  doc.text(`Report period  |  ${fmtPdfText(report.periodLabel || "-")}`, textX, 30.5);

  let y = bandH + 5;
  if (extraMetaLines.length) {
    doc.setFont(pdfFont, "normal");
    doc.setFontSize(6.8);
    doc.setTextColor(...PALETTE.muted);
    extraMetaLines.forEach((line, i) => {
      const t = line.length > 118 ? `${line.slice(0, 115)}...` : line;
      doc.text(fmtPdfText(t), margin, y + i * 3.1);
    });
    y = y + extraMetaLines.length * 3.1 + 5;
  } else {
    y = bandH + 6;
  }

  const tableFont = { font: pdfFont, fontStyle: "normal" };
  const summaryRow1 = [
    { content: `Total collected\n${fmtInr(m.totalCollectedAmount)}`, styles: { ...tableFont, fillColor: [239, 246, 255], textColor: PALETTE.ink, fontStyle: "bold", fontSize: 8.5 } },
    { content: `Successful\n${String(m.successfulCollections ?? 0)}`, styles: { ...tableFont, fillColor: [236, 253, 245], textColor: PALETTE.success, fontStyle: "bold", fontSize: 8.5 } },
    { content: `Pending dues\n${String(m.pendingCollection ?? 0)}`, styles: { ...tableFont, fillColor: [254, 243, 199], textColor: PALETTE.warn, fontStyle: "bold", fontSize: 8.5 } },
    { content: `Skipped\n${String(m.skippedCollections ?? 0)}`, styles: { ...tableFont, fillColor: [241, 245, 249], textColor: PALETTE.muted, fontStyle: "bold", fontSize: 8.5 } },
  ];
  const nl = Number(m.newLoansInRangeCount ?? 0);
  const nla = Number(m.newLoansInRangeAmount ?? 0);
  const summaryRow2 = [
    {
      content: `New loans\n${nl} | ${fmtInr(nla)}`,
      styles: { ...tableFont, fillColor: [239, 246, 255], textColor: PALETTE.ink, fontStyle: "bold", fontSize: 8.5 },
    },
    {
      content: `Outstanding\n${fmtInr(m.currentTotalOutstanding)}`,
      styles: { ...tableFont, fillColor: [254, 243, 199], textColor: PALETTE.warn, fontStyle: "bold", fontSize: 8.5 },
    },
    {
      content: `Net (approx.)\n${fmtInr(m.netCashApprox)}`,
      styles: { ...tableFont, fillColor: [236, 253, 245], textColor: PALETTE.success, fontStyle: "bold", fontSize: 8.5 },
    },
    { content: "", styles: { ...tableFont, fillColor: PALETTE.surface, textColor: PALETTE.muted, fontStyle: "normal", fontSize: 8 } },
  ];

  autoTable(doc, {
    startY: y,
    body: [summaryRow1, summaryRow2],
    theme: "plain",
    styles: { ...tableFont, cellPadding: 3.5, valign: "middle", minCellHeight: 16 },
    margin: { left: margin, right: margin },
    tableWidth: contentW,
  });

  y = doc.lastAutoTable.finalY + 6;

  doc.setFont(pdfFont, "bold");
  doc.setFontSize(9);
  doc.setTextColor(...PALETTE.ink);
  doc.text("Collection portfolio", margin, y);
  y += 2;

  const rows = (report.detailRows || []).map((row) => {
    const centerParts = [row.dayCenter, row.subCenter].filter((p) => p && String(p).trim() && String(p).trim() !== "--");
    const center = centerParts.length ? centerParts.join(" | ") : "-";
    const st = rowDisplayStatus(row);
    return {
      rowData: [
        fmtPdfText(center),
        fmtPdfText(row.customerName || "-"),
        fmtPdfText(row.phoneNumber || "-"),
        fmtInr(row.loanAmount),
        fmtInr(row.totalPayable),
        fmtInr(row.totalCollected),
        fmtInr(row.outstanding),
        fmtDate(row.dueDate),
        st.label,
      ],
      tone: st.tone,
    };
  });

  const body = rows.map((r) => r.rowData);

  const colW = {
    center: 24,
    customer: 32,
    phone: 21,
    loan: 18,
    payable: 18,
    collected: 17,
    outstanding: 18,
    due: 16,
    status: 22,
  };

  autoTable(doc, {
    startY: y + 2,
    head: [["Center", "Customer name", "Phone", "Loan amt", "Payable", "Collected", "Outstanding", "Due date", "Status"]],
    body,
    theme: "striped",
    showHead: "everyPage",
    tableWidth: contentW,
    headStyles: {
      font: pdfFont,
      fillColor: PALETTE.headBg,
      textColor: PALETTE.headText,
      fontStyle: "bold",
      fontSize: 7.2,
      halign: "center",
      valign: "middle",
      overflow: "linebreak",
    },
    styles: {
      font: pdfFont,
      fontSize: 7.2,
      cellPadding: 1.6,
      lineColor: PALETTE.line,
      lineWidth: 0.15,
      valign: "middle",
      overflow: "linebreak",
    },
    alternateRowStyles: { fillColor: PALETTE.surfaceAlt },
    columnStyles: {
      0: { cellWidth: colW.center, halign: "left" },
      1: { cellWidth: colW.customer, halign: "left" },
      2: { cellWidth: colW.phone, halign: "left" },
      3: { halign: "right", cellWidth: colW.loan },
      4: { halign: "right", cellWidth: colW.payable },
      5: { halign: "right", cellWidth: colW.collected },
      6: { halign: "right", cellWidth: colW.outstanding },
      7: { cellWidth: colW.due, halign: "center" },
      8: { cellWidth: colW.status, halign: "center", minCellWidth: colW.status },
    },
    margin: { left: margin, right: margin, bottom: 18 },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 8) {
        const tone = rows[data.row.index]?.tone || "gray";
        const s = statusCellStyle(tone);
        Object.assign(data.cell.styles, {
          fillColor: s.fillColor,
          textColor: s.textColor,
          fontStyle: s.fontStyle,
        });
      }
    },
  });

  drawAllFooters(doc, generatedLabel, pdfFont);
  return doc;
}

/**
 * @param {object} report
 * @param {object} [options]
 */
export async function downloadLoanCollectionReportPdf(report, options = {}) {
  const doc = await buildLoanCollectionReportDoc(report, options);
  const stamp = new Date().toISOString().slice(0, 10);
  doc.save(`collection-report-${stamp}.pdf`);
}

/**
 * @param {object} report
 * @param {object} [options]
 */
export async function printLoanCollectionReportPdf(report, options = {}) {
  const doc = await buildLoanCollectionReportDoc(report, options);
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank", "noopener,noreferrer");
  const cleanup = () => URL.revokeObjectURL(url);
  if (!win) {
    cleanup();
    await downloadLoanCollectionReportPdf(report, options);
    return;
  }
  setTimeout(() => {
    try {
      win.focus();
      win.print();
    } catch {
      /* ignore */
    }
  }, 650);
  setTimeout(cleanup, 120_000);
}
